version: '{build}'
max_jobs: 1
image: WMF 5
#clone_depth: 5
branches:
  only:
  - master
#build:
#  verbosity: minimal

environment:
  # Github token to commit pushed packages to repository
  github_user_repo: derwasp/aws-codebuild-official-images
  github_api_key:
    secure: qCzmAZw5Jo9ttv5Qz5PHb3BrNGJ/4bS0pcmIKN0bBDY3VnJNC2Fl0ISaTopB0cDZ #https://ci.appveyor.com/tools/encrypt
init:
- git config --global user.email "nbcwasp@gmail.com"
- git config --global user.name "derwasp"
- git config --global core.safecrlf false

install:

build_script:
- ps: |
    function containsLike($elements, $str){
        foreach($element in $elements) { if($element -like $str) { return $True; } }
        return $False;
    }

    Write-Host ("Cloning the official aws repo..")

    git clone -q https://github.com/aws/aws-codebuild-docker-images/

    $dockerDirectories = Get-ChildItem -Path .\aws-codebuild-docker-images\ubuntu\ -Filter Dockerfile -Recurse -File | ForEach-Object {
        [System.IO.Path]::GetFullPath($_.Directory)
    }

    Write-Host ("Adding git credentials..")
    git config --global credential.helper store
    Add-Content "$env:USERPROFILE\.git-credentials" "https://${env:github_api_key}:x-oauth-basic@github.com`n"

    Write-Host ("Cloning the temporary repo..")
    git clone -q https://github.com/derwasp/aws-codebuild-official-images tmp

    $listBranches = git ls-remote -q --heads
    pushd tmp

    foreach ($directory in $dockerDirectories) {
        $version = [System.IO.Path]::GetFileName($directory)
        $image = [System.IO.Path]::GetFileName([System.IO.Path]::GetDirectoryName($directory))
        $tag = $image + "-" + $version

        Write-Host ("Tag " + $tag + " in " + $directory)

        if (containsLike $listBranches ("*/" + $tag)) {
            Write-Host ("Existing branch")
            git checkout -q $tag
        }
        else {
            Write-Host ("New branch")
            git checkout -q -b $tag
        }

        Get-ChildItem -Force -Path . -Recurse |
        Select -ExpandProperty FullName |
        Where {$_ -notlike '*\.git*'} |
        Sort length -Descending |
        Remove-Item -Force

        Copy-item -Force -Recurse -Verbose ($directory + "\*") -Destination .

        git add -A
        git commit -am ($tag + "[skip appveyor]")
        Write-Host ("Pushing " + $tag)
        git push -q origin $tag
    }

    popd

